### ISSUE TITLE
Additional components

### ISSUE THREAD

**Issue by sergy79** [nootn/MVC-Mega-Forms#3]
Hi, can you list out the additional components, looks like a cool plugin :+1: 

thx

**Comment by nootn** [comment]
Hi, thanks for the comment.  You can check out the features here: http://nootn.github.io/MVC-Mega-Forms

I would really only recommend using it for smallish intranet applications, not public facing applications.  That is what it was designed for.  Some of the code is pretty "quick and dirty", I just whipped it up to make my day job easier :)  There is not much consideration for performance with some wacky JQuery stuff going on!

Honestly I don't have grand plans to maintain it, I don't really use JQuery anymore, I am using ReactJS at the moment so I am more likely to start some projects in that, however I have a lot of legacy code at my workplace using this library so it may get some love every now and then!

There are other libraries that do some similar bits, such as for layouts check out Chamelion Forms: https://github.com/MRCollective/ChameleonForms - it is far better maintained than this library!  

Probably the only cool thing in here is the Change Visually concept.  It allows you to define which fields will be shown/enabled when, and the logic can run on the client and server.  So for example if a required field is hidden on the screen when some condition is met, then when you validate on the server, you can get it to ignore the fact that field was required (because logically it was not).  That is using an extension method on ModelState that actually executes javascript logic on the server side the same as the client side to determine which fields were editable.  I think that is the only feature I have not really seen in other .NET libraries.
